
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://www.ottrproject.org/more_features.html#giving-credits-to-contributors).

&nbsp;
&nbsp;

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor(s)|[Carrie Wright]|
|PI of Project|[Ava Hoffman]|
|Content Editor(s)/Reviewer(s) | Checked your content|
|**Production**||
|Content Publisher(s)| [Carrie Wright]|
|Content Publishing Reviewer(s)| Reviewed overall content and aesthetics on publishing platform|
|**Technical**||
|Course Publishing Engineer(s)| [Carrie Wright]|
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright], [Ava Hoffman]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Ava Hoffman], [Candace Savonen], [Katherine Cox]|
|Package Developers ([ottrpal]) | [Candace Savonen], [Ava Hoffman], [Howard Baek], [Kate Isaac], [Carrie Wright], [John Muschelli]|
|**Art and Design**||
|Illustrator(s)| [Carrie Wright], [Elizabeth Humphries]|
|**Funding**||
|Funder(s)| DaSEH is funded by the National Institute of Environmental Health Sciences 1R25ES035590-01.|
|Funding Staff| Allison Peters|

&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```

<!-- Author information -->

[FirstName LastName]: link to personal website
[John Muschelli]: https://johnmuschelli.com/
[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/
[Ava Hoffman]: https://www.avahoffman.com/
[Howard Baek]: https://www.linkedin.com/in/howard-baik/
[Elizabeth Humphries]: https://www.linkedin.com/in/elizabeth-humphries-61202a103/
[Kate Isaac]: https://kweav.github.io/
[Katherine Cox]: https://katherinecox.github.io/

<!-- Links -->

[ottrpal]: https://github.com/ottrproject/ottrpal

<!-- Fill out this table using these instructions: https://www.ottrproject.org/more_features.html#giving-credits-to-contributors



|Content Publisher|[Ira Gooding]|
...
[Ira Gooding]: https://publichealth.jhu.edu/faculty/4130/ira-gooding
-->
